import { expect, test } from '@playwright/test'

test('Data Page 清晰显示 Demo、来源、版本、数量和素材状态', async ({ page }) => {
  await page.goto('/data')
  await expect(page.getByTestId('demo-status')).toContainText('DEMO 示例数据')
  await expect(page.getByText('Data Status')).toBeVisible()
  await expect(page.getByText('Asset Status')).toBeVisible()
  await expect(page.getByText('ninja-bp-arena 仓库内置示例')).toBeVisible()
  await expect(page.getByText(/28 名忍者 · 4 个秘卷 · 8 个通灵/)).toBeVisible()
})

test('资源搜索、筛选、锁定原因与键盘导航可用', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('banner').getByRole('button', { name: '开始 BP' }).click()
  await page.getByRole('button', { name: '开始比赛' }).click()
  await expect(page.getByLabel('搜索忍者')).toBeVisible()
  await page.keyboard.press('Slash')
  await expect(page.getByLabel('搜索忍者')).toBeFocused()
  await page.getByLabel('搜索忍者').fill('鸣人')
  await expect(page.getByRole('button', { name: /漩涡鸣人（可选）/ })).toBeVisible()
  await page.getByRole('button', { name: '清除搜索' }).click()
  await page.getByRole('button', { name: 'S', exact: true }).click()
  await expect(page.getByRole('button', { name: /漩涡鸣人（可选）/ })).toBeVisible()
  await page.getByRole('button', { name: /漩涡鸣人（可选）/ }).click()
  const locked = page.getByRole('button', { name: /漩涡鸣人（已禁用）/ })
  await expect(locked).toHaveAttribute('aria-disabled', 'true')
  await expect(locked).toHaveAttribute('title', /本局已被禁用/)
  await locked.focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.locator('[data-resource-card]:focus')).toHaveCount(1)
})

test.describe('390px Full Loadout workspace', () => {
  test.use({ viewport: { width: 390, height: 844 } })
  test('阶段始终可见且 Team Sheet 可展开，无横向溢出', async ({ page }) => {
    await page.goto('/')
    await page.getByRole('button', { name: '菜单' }).click()
    await page.getByRole('banner').getByRole('button', { name: '开始 BP' }).click()
    await page.getByLabel('规则模板').selectOption('FULL_LOADOUT')
    await page.getByRole('button', { name: '开始比赛' }).click()
    await expect(page.getByRole('tab', { name: /忍者 · 当前/ })).toBeVisible()
    await page.getByRole('tab', { name: '秘卷' }).click()
    await expect(page.getByRole('button', { name: /护身结界（示例）.*当前阶段为忍者/ })).toHaveCount(1)
    await page.getByRole('button', { name: /BLUE/ }).first().click()
    await expect(page.locator('aside:visible')).toHaveCount(2)
    const size = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, client: document.documentElement.clientWidth }))
    expect(size.scroll).toBeLessThanOrEqual(size.client + 1)
  })
})
